Fix for #21
kgar/foundry-vtt-tidy-5e-sheets pull request #163
Opened 2023-12-12 23:50 UTC by voodoofrog

I've added two settings to the main config for old style attribute tabbing, and old style HP tabbing. I can condense this down to one setting if preferred.

Because the original sheets were using different controls they used `type=hidden` but because this sheet uses more semantically appropriate controls, I've instead removed them from teh tab order via `tabindex=-1`.

2023-12-15 23:00 UTC, kgar requested changes
I've got a few minor requests regarding the wording of the localization keys / values and the setting variable names.
All in all, this looks great!

2023-12-15 23:00 UTC, kgar commented on public/lang/en.json
> +    "name": "Use old attribute keyboard tabbing",
I recommend a name like "Use default sheet attribute keyboard tabbing", mainly because OG Tidy will lose a lot of mind share when this one takes over for more than several months. However, I have received a lot of requests to make things work like the default sheets, and I think that will make more immediate sense to users.

Likewise for the descriptions, can we cut any references to old Tidy?

2023-12-15 23:00 UTC, kgar commented on src/settings/settings.ts
> +          name: 'T5EK.Settings.UseOldAttributeTabbing.name',
Ditto for the localization keys, making the focus on achieving default sheet behavior, so something like "T5EK.Settings.UseDefaultSheetAttributeTabbing.name"

2023-12-15 23:02 UTC, kgar commented
I apologize for the wait on the review. I put comments in like 3 days ago, but I didn't know I needed to complete the review for them to post. I'll get that right next time.

2023-12-16 13:51 UTC, voodoofrog commented on public/lang/en.json
> +    "name": "Use old attribute keyboard tabbing",
Absolutely.

2023-12-16 14:11 UTC, voodoofrog commented
> I apologize for the wait on the review. I put comments in like 3 days ago, but I didn't know I needed to complete the review for them to post. I'll get that right next time.

Yeah no worries. The review process in GitHub is a bit different from what I'm used to too, I usually work with GitLab.

2023-12-16 14:12 UTC, voodoofrog commented
I've updated with changes to bring it in line with your requests.

2023-12-16 17:14 UTC, kgar approved these changes
Fantastic work. I will be using these settings, myself.

Thank you for contributing!

2023-12-16 17:14 UTC, merged